stages:
 - package
 - release
 - upload

package-debian-stretch:
  image: debian:stretch
  stage: package
  only:
    - tags
  script:
    - apt update && apt -y --no-install-recommends install gcc checkinstall libpurple-dev libglib2.0-dev libjson-glib-dev libnss3-dev libsecret-1-dev lintian
    - cd steam-mobile/ && checkinstall --pkgname=pidgin-opensteamworks --arch=amd64 --pkglicense=GPL-3.0 --pkgsource https://github.com/EionRobb/pidgin-opensteamworks --pkgversion=${CI_COMMIT_TAG}-stretch0 --requires="libpurple0,libglib2.0-0,libjson-glib-1.0-0,libnss3,libsecret-1-0"
    - lintian *.deb || true
    - mv *.deb ../
  artifacts:
    paths:
      - ./*.deb

package-debian-buster:
  image: debian:buster-backports
  stage: package
  only:
    - tags
  script:
    - apt update && apt -y --no-install-recommends install gcc checkinstall libpurple-dev libglib2.0-dev libjson-glib-dev libnss3-dev libsecret-1-dev lintian
    - cd steam-mobile/ && checkinstall --pkgname=pidgin-opensteamworks --arch=amd64 --pkglicense=GPL-3.0 --pkgsource https://github.com/EionRobb/pidgin-opensteamworks --pkgversion=${CI_COMMIT_TAG}-buster0 --requires="libpurple0,libglib2.0-0,libjson-glib-1.0-0,libnss3,libsecret-1-0"
    - lintian *.deb || true
    - mv *.deb ../
  artifacts:
    paths:
      - ./*.deb

publish-release:
  script: echo "publising release $CI_COMMIT_TAG"
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  release:
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG"
  only:
    - tags

upload_packages:
  stage: upload
  image: curlimages/curl:latest
  only:
    - tags
  script:
    - "curl --header 'JOB-TOKEN: ${CI_JOB_TOKEN}' --upload-file pidgin-opensteamworks_${CI_COMMIT_TAG}-stretch0_amd64.deb ${PACKAGE_REGISTRY_URL}/pidgin-opensteamworks_${CI_COMMIT_TAG}-stretch0_amd64.deb"
    - "curl --header 'JOB-TOKEN: ${CI_JOB_TOKEN}' --upload-file pidgin-opensteamworks_${CI_COMMIT_TAG}-buster0_amd64.deb ${PACKAGE_REGISTRY_URL}/pidgin-opensteamworks_${CI_COMMIT_TAG}-buster0_amd64.deb"
