stages:
 - package
 - release

package-debian-stretch:
  image: debian:stretch
  stage: package
  only:
    - tags
  script:
    - apt update && apt -y --no-install-recommends install gcc checkinstall libpurple-dev libglib2.0-dev libjson-glib-dev libnss3-dev libsecret-1-dev lintian
    - cd steam-mobile/ && checkinstall --pkgname=pidgin-opensteamworks --arch=amd64 --pkglicense=GPL-3.0 --pkgsource https://github.com/EionRobb/pidgin-opensteamworks --pkgversion=${CI_COMMIT_REF}-stretch0 --requires="libpurple0,libglib2.0-0,libjson-glib-1.0-0,libnss3,libsecret-1-0"
    - lintian *.deb || true
    - mv *.deb ../
  artifacts:
    paths:
      - ./*.deb

package-debian-buster:
  image: debian:buster-backports
  stage: package
  only:
    - tags
  script:
    - apt update && apt -y --no-install-recommends install gcc checkinstall libpurple-dev libglib2.0-dev libjson-glib-dev libnss3-dev libsecret-1-dev lintian
    - cd steam-mobile/ && checkinstall --pkgname=pidgin-opensteamworks --arch=amd64 --pkglicense=GPL-3.0 --pkgsource https://github.com/EionRobb/pidgin-opensteamworks --pkgversion=${CI_COMMIT_REF}-buster0 --requires="libpurple0,libglib2.0-0,libjson-glib-1.0-0,libnss3,libsecret-1-0"
    - lintian *.deb || true
    - mv *.deb ../
  artifacts:
    paths:
      - ./*.deb

publish-release:
  script: echo "publising release $CI_COMMIT_TAG"
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  release:
    tag_name: $CI_COMMIT_TAG
    description: "$CI_COMMIT_TAG"
  only:
    - tags